config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :articles
    get 'signup', to: 'users#new'
    resources :users
    #Aqui nao usaremos resources, teremos que fazer na mao
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord 
    belongs_to :user
    validates :title, presence: true, length: { minimum: 6,   maximum: 100 }
    validates :description, presence: true, length: { minimum: 6 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles
    validates :username, presence: true, uniqueness: {case_sensitive: false }, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def index 
       @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def show 
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
          flash[:notice] = "Article was created successfully"
          redirect_to @article
        else 
          render 'new'
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was edited!"
            redirect_to articles_path
        else 
            render "edit"
        end
    end

    def destroy 
        @article.destroy
        redirect_to @article
    end

    private 
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, :created_at, :updated_at)
    end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end
   
    def about 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
       
    end 

    def create    
        user = User.find_by(email: params[:session][:email].downcase)
        # if user && user.authenticate(params[:session][:password])
        if user 
          session[:user_id] = user.id
          flash[:notice] = "Logged in successfully"
          redirect_to user
        else
          flash.now[:alert] = "There was something wrong with your login details"
          render 'new'
        end
      end

    def destroy
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        @users = User.all
     end

     def show 
        @user = User.find(params[:id])
     end
 

    def new
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save 
            redirect_to @user
        else 
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "User was edited!"
            redirect_to articles_path
        else 
            render "edit"
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password_digest)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
      email_address = user.email.downcase
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
  
  end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_errors.html.erb
    <% if @article.errors.any?  %>
        <h2> Something is wrong: </h2>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end %>
        </ul>

    <% end %>

app/views/articles/_form.html.erb
    <%= render 'errors' %>

    
    <div class="create_card">


    <%= form_with(model: @article, local: true) do |f| %>

        <div class="labeldiv"> 
            <%= f.label :title %>
            <br>
            <%= f.text_field :title %>
        </div>

        <div class="labeldiv">
            <%= f.label :description %>
            <br>
            <%= f.text_area :description %>
        </div>

        <div class="labeldiv" id="submitdiv">
            <%= f.submit %>
        </div>

    <% end %>

    </div>

app/views/articles/edit.html.erb
<div class="container" id="edit_container"> 

<h1> Edit Article </h1>

<%= render 'form' %>

   <div class="back">
        <div> 
        <%= link_to 'Back', articles_path %> 
        </div>
     </div>

</div>

app/views/articles/index.html.erb
<div class="container"> 




    <div class="articles_list">

     

        <div class="article_title">
            <div id="create" > 
                <div> <%= link_to 'Create!', new_article_path %>  </div>
            </div> 
            <h1> Listing all articles</h1>
        </div>

        

       

            <div class="card_list">


                    <% @articles.each do |article| %>

                    <div class="card">

                        <div class="user_section">
                           <h3> by <%= article.user.username if article.user %> </h4>
                         </div>

                        <div class="article_section">

                            <h2> <%= article.title %> </h2>
                            <h3> <%= article.description %> </h3>

                            <div class="control_section">
                    
                               <div> <%= link_to 'View', article_path(article) %>  </div> 
                               <div> <%= link_to 'Edit', edit_article_path(article) %> </div>
                               <div> <%= link_to 'Delete', article_path(article), method: :delete %> </div>
                            </div>

                            <div class="hour_section">
                                <h4>  Created about <%= time_ago_in_words(article.created_at) %>  ago, edited about <%= time_ago_in_words(article.updated_at) %>  ago</h4>
                            </div>

                        </div>

   




                    </div>

                           
                    <% end %>


            </div>

            <%= will_paginate @articles %> 

    </div>

</div>

app/views/articles/new.html.erb
<div class="container" id="create_container"> 

    <h1> Create a new article </h1>

    <div>
     <%= render 'form' %>
    </div>

    <div class="back">
        <div> 
        <%= link_to 'Back', articles_path %> 
        </div>
     </div>

</div>

app/views/articles/show.html.erb
<%= render 'layouts/messages' %>

<div class="container"> 

    <div class="articles_list">


            <div class="article_title">
            <h1> Showing articles details! </h1>
            </div>

            <div class="card_list">

                <div class="card">

                    <div class="user_section">
                    <h3> <%= @article.user.username %> </h4>
                    </div>

                    <div class="article_section">

                        <h2> Title: <%= @article.title %> </h2>
                        <h3> Description: <%= @article.description %></h3>

                    </div>

                    <div class="control_section">

                        <div> <%= link_to 'Edit', edit_article_path(@article) %> </div>

                        <div> <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "are you sure?" } %> </div>

                    </div>

                    <div class="hour_section">
                        <h4>  Created about <%= time_ago_in_words(@article.created_at) %>ago, edited about <%= time_ago_in_words(@article.updated_at) %> ago</h4>
                    </div>



            </div>

       




    </div>

        <div class="back">
            <div> 
            <%= link_to 'Back', articles_path %> 
            </div>
        </div> 

    </div>

</div>

app/views/layouts/_footer.html.erb
<div class="footer">

    <div class="footer_container">

        <div>
            <p> Gabriel Guerra @ 2021 </p>
        </div>

        <div>
            <p> The Complete Ruby On Rails Udemy Course </p>
        </div>
    </div>

</div>

app/views/layouts/_header.html.erb
  <div class="header"> 
    <div class="header_container">

      <div class="logo_nav">
        <div class="logo"> 
          <%= link_to "Alpha Blog", root_path %> 
        </div>

        
          <ul> 
            <li> <%= link_to "Articles", articles_path %> </li>
            <li> <%= link_to "Users", users_path %> </li>
            <li> <%= link_to "About", about_path %> </li>
            <li> <%= link_to "Login", login_path %> </li>
          </ul>
      </div>

    <div class="search">
      <input type="text" placeholder="Search for something"> 
      <button type="submit"> Search </button>
    </div> 



     </div>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %> 
    <%= msg %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
 <% end %>
 

    <% if flash[:alert] %>
    <div class="notice"><%= flash[:alert] %></div>
    <% end %>


  <%= render 'layouts/header' %>

    <%= yield %>

   <%= render 'layouts/footer' %> 
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">

    <h2> this is the about page </h2>

</div>

app/views/pages/home.html.erb
<main>
    <div class="container"> 

        <div class="jumbotron"> 
            <div class="jumbotron-text"> 
                <div>
                    <h1> Alpha Blog </h1>
                    <p> This is a Rails application! </p>
                    <button> <%= link_to "Sign Up", signup_path %> </button>
                </div>
            </div>
        </div>

    </div>
</main>

app/views/users/_errors.html.erb
    <% if @user.errors.any?  %>
        <h2> Something is wrong: </h2>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end %>
        </ul>

    <% end %>

app/views/users/_form.html.erb
  <%= render 'errors' %>
    
    <div class="create_card">


    <%= form_with(model: @user, local: true) do |f| %>

        <div class="labeldiv"> 
            <%= f.label :username %>
            <br>
            <%= f.text_field :username %>
        </div>

        <div class="labeldiv">
            <%= f.label :email %>
            <br>
            <%= f.email_field :email %>
        </div>

        <div class="labeldiv">
            <%= f.label :password_digest, "Password" %>
            <br>
            <%= f.password_field :password_digest %>
        </div>

        <div class="labeldiv" id="submitdiv">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update account" ) %>
        </div>

    <% end %>

    </div>

app/views/users/edit.html.erb
<div class="container" id="create_container"> 

    <h1> Sign Up </h1>

    <div>
     <%= render 'form' %>
    </div>

    <div class="back">
        <div> 
        <%= link_to 'Back', users_path %>  
        </div>
     </div>

</div>

app/views/users/index.html.erb
<div class="container"> 

    

    <div class="articles_list">


     

        <div class="article_title">
            <div id="create" > 
                <div> <%= link_to 'Create!', new_user_path %>  </div>
            </div> 
            <h1> Listing all users</h1>
        </div>

       

       

            <div class="card_list">


                    <% @users.each do |user| %>

                    <%= gravatar_for user, size: 150 %>

                    <div class="card">

                        <div class="user_section">
                           <h3>  <%= user.username if user %> </h3>
                            
                         </div>

                        <div class="article_section">

                            <h2> <%= user.email %> </h2>
                           
                            <div class="control_section">
                    
                                <div> <%= link_to 'View', user_path(user) %> </div>
                               <div> <%= link_to 'Edit', edit_user_path(user) %> </div>
                               <div> <%= link_to 'Delete', user_path(user), method: :delete %> </div>
                            </div>

                            <div class="hour_section">
                                <h4>  Created about <%= time_ago_in_words(user.created_at) %>  ago, edited about <%= time_ago_in_words(user.updated_at) %>  ago</h4>
                            </div>

                        </div>

   




                    </div>

                           
                    <% end %>


            </div>

    </div>

</div>

app/views/users/new.html.erb
<div class="container" id="create_container"> 

    <h1> Sign Up </h1>

    <div>
     <%= render 'form' %>
    </div>

    <div class="back">
        <div> 
        <%= link_to 'Back', root_path %> 
        </div>
     </div>

</div>

app/views/users/show.html.erb
<%= render 'layouts/messages' %>

<div class="container"> 

    <div class="articles_list">


            <div class="article_title">
            <h1> Showing user details! </h1>
            </div>

            <div class="card_list">

            <%= gravatar_for @user, size: 200 %>



                <div class="card">

                    <div class="user_section">
                    <h3> <%= @user.username %> </h3>
                     <h3>  <%= @user.email %> </h3>
                    </div>

                    <div class="article_section">



                         <% @user.articles.each do |article| %> 


                         <h2> <%= article.title %> </h2>

                         <p> <%= article.description %> </p>


                         <% end %>

                   
                    </div>

                    <div class="control_section">

                        <div> <%= link_to 'Edit', edit_user_path(@user) %> </div>

                        <div> <%= link_to 'Delete', user_path(@user), method: :delete, data: { confirm: "are you sure?" } %> </div>

                    </div>

                    <div class="hour_section">
                        <h4>  Created about <%= time_ago_in_words(@user.created_at) %>ago, edited about <%= time_ago_in_words(@user.updated_at) %> ago</h4>
                    </div>



            </div>

       




    </div>

        <div class="back">
            <div> 
            <%= link_to 'Back', users_path %> 
            </div>
        </div> 

    </div>

</div>